# Generated by Django 5.2.2 on 2025-06-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_alter_car_manufacturer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ("manufacturer",)},
        ),
    ]
